### ISSUE TITLE
Yubikey button touch not workling via NFC

### ISSUE THREAD

**Issue by anothernickname536** [pp3345/ykDroid#18]
Hi,
i use ykDrod on Android with Keepass.
Connected via USB-C I get asked to touch the Yubikey before the database opens. So far so good, however using NFC the touch of the golden Yubikey Button is not required.
Is that a security issue, or user problem?
Thanks!
[Android 10 / Keepass2Android (1.08c-1) / ykDroid (1.2.1) / YubiKey 5 NFC]

![grafik](https://user-images.githubusercontent.com/77550047/104821584-34fa4b80-583d-11eb-8895-35077299da62.png)

**Comment by pp3345** [comment]
This is by design and not ykDroid's fault. YubiKeys simply work that way, they only really enforce pressing the button when used via USB. This also makes sense when you think about it: NFC is designed for very short contact times and swiping the YubiKey across the NFC sensor already requires physical interaction, so there is no need to press another physical button to get permission for the process from the user.
