### ISSUE TITLE
Keepass2Android doesn't recognize ykDroid.

### ISSUE THREAD

**Issue by tryptichon** [pp3345/ykDroid#4]
Is is just me, or do newer versions of Keepass2Android only work with the YubiChallenge - App? My installation of Keepass2Android doesn't recognize ykDroid and wants to install YubiChallenge instead.

Android 7.1 on Sony Xperia Z5 Compact
Keepass2Android 1.05e
ykDroid 1.0.1

**Comment by wbedard** [comment]
Given the application versions you are citing, it's likely just you (or a very small minority of users...).  In fact, starting with KP2A 1.0.6, the dev removed his implementation of YubiChallenge (the standalone app from the store isn't required...) and instead requires ykDroid to be installed.

Assuming that you aren't seeing ykDroid prompt for which slot to use when opening a database, you are the second user I have heard to experience that issue.  Since this is a very recent change, there are almost certainly some bugs that still need to get ironed out.  However, the direction moving forward is definitely to leverage ykDroid for NFC support.

**Comment by pp3345** [comment]
What @wbedard says, is correct. Keepass2Android supports ykDroid starting from version 1.06 (which should afaik already be published on Google Play). When running 1.05, YubiChallenge is used instead.

**Comment by tryptichon** [comment]
Alright. Waiting for Keepass2Android 1.0.6 update on Google Play Store then. I'm in Germany, so the update might not yet be on the store I have access to. Thanks for the info.

**Comment by pp3345** [comment]
You may enroll for Keepass2Android's beta program using the Play Store app on your device, then you should be able to update to a pre-release version of 1.06. I've checked again and it seems that 1.06 isn't yet published as a stable release, sorry.

Closing this though as it's not really a ykDroid issue. Feel free to open another one if you encounter any problems with ykDroid.
